///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_123
{
    public partial class Login
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        
        public void WaitForElementToBeDisplayed(RxPath rxPath, Duration timeInterval){
        	 Duration waitTime = 3000;
            Duration totalTimeout = 0;
            Element webElement = null;
            while (!
            (Host.Local.TryFindSingle
            (rxPath, waitTime, out webElement)))
            {
                System.Threading.Thread.Sleep(waitTime.Milliseconds);
                totalTimeout = totalTimeout + waitTime;
                if (totalTimeout.Milliseconds > timeInterval.Milliseconds)
                {
                    throw new ElementNotFoundException("Elemet not found");
                } 
            }
        	
        }

    }
}
