///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_123
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_123Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("0cde08bf-7c1b-4b27-a864-7394a08555a6")]
    public partial class Test_123Repository : RepoGenBaseFolder
    {
        static Test_123Repository instance = new Test_123Repository();
        Test_123RepositoryFolders.LoginFolder _login;

        /// <summary>
        /// Gets the singleton class instance representing the Test_123Repository element repository.
        /// </summary>
        [RepositoryFolder("0cde08bf-7c1b-4b27-a864-7394a08555a6")]
        public static Test_123Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_123Repository() 
            : base("Test_123Repository", "/", null, 0, false, "0cde08bf-7c1b-4b27-a864-7394a08555a6", ".\\RepositoryImages\\Test_123Repository0cde08bf.rximgres")
        {
            _login = new Test_123RepositoryFolders.LoginFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0cde08bf-7c1b-4b27-a864-7394a08555a6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Login folder.
        /// </summary>
        [RepositoryFolder("3e45edcd-c5da-47d6-b048-9b682d989609")]
        public virtual Test_123RepositoryFolders.LoginFolder Login
        {
            get { return _login; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Test_123RepositoryFolders
    {
        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("3e45edcd-c5da-47d6-b048-9b682d989609")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            Test_123RepositoryFolders.MedwayAppFolder _medway;
            Test_123RepositoryFolders.PagesFolder _pages;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "3e45edcd-c5da-47d6-b048-9b682d989609", "")
            {
                _medway = new Test_123RepositoryFolders.MedwayAppFolder(this);
                _pages = new Test_123RepositoryFolders.PagesFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e45edcd-c5da-47d6-b048-9b682d989609")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Medway folder.
            /// </summary>
            [RepositoryFolder("ecf998a0-26f9-4ecd-ae60-962dd1223516")]
            public virtual Test_123RepositoryFolders.MedwayAppFolder Medway
            {
                get { return _medway; }
            }

            /// <summary>
            /// The Pages folder.
            /// </summary>
            [RepositoryFolder("6c85d5fe-314c-4a76-b5db-65d7fe984dd9")]
            public virtual Test_123RepositoryFolders.PagesFolder Pages
            {
                get { return _pages; }
            }
        }

        /// <summary>
        /// The MedwayAppFolder folder.
        /// </summary>
        [RepositoryFolder("ecf998a0-26f9-4ecd-ae60-962dd1223516")]
        public partial class MedwayAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new Medway  folder.
            /// </summary>
            public MedwayAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Medway", "/form[@controlname='LoginForm']/container/container[@controlname='layoutControl1']", parentFolder, 30000, null, true, "ecf998a0-26f9-4ecd-ae60-962dd1223516", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", "element[@controlname='textName']", 30000, null, "704fbbf1-0a8a-4059-a86c-c2f45b3e7389");
                _passwordInfo = new RepoItemInfo(this, "Password", "element[@controlname='textPassword']", 30000, null, "5660e0e0-da2d-4eb0-9b8c-10ad05e4ed16");
                _buttonInfo = new RepoItemInfo(this, "Button", "element[@controlname='buttonLogin']/button[@accessiblename='Login']", 30000, null, "8806c4a4-484a-4fe1-b604-39162aa39bbb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ecf998a0-26f9-4ecd-ae60-962dd1223516")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ecf998a0-26f9-4ecd-ae60-962dd1223516")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("704fbbf1-0a8a-4059-a86c-c2f45b3e7389")]
            public virtual Ranorex.Unknown UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("704fbbf1-0a8a-4059-a86c-c2f45b3e7389")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("5660e0e0-da2d-4eb0-9b8c-10ad05e4ed16")]
            public virtual Ranorex.Unknown Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("5660e0e0-da2d-4eb0-9b8c-10ad05e4ed16")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("8806c4a4-484a-4fe1-b604-39162aa39bbb")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("8806c4a4-484a-4fe1-b604-39162aa39bbb")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

        /// <summary>
        /// The PagesFolder folder.
        /// </summary>
        [RepositoryFolder("6c85d5fe-314c-4a76-b5db-65d7fe984dd9")]
        public partial class PagesFolder : RepoGenBaseFolder
        {
            Test_123RepositoryFolders.LoginPageAppFolder _loginpage;

            /// <summary>
            /// Creates a new Pages  folder.
            /// </summary>
            public PagesFolder(RepoGenBaseFolder parentFolder) :
                    base("Pages", "", parentFolder, 0, null, false, "6c85d5fe-314c-4a76-b5db-65d7fe984dd9", "")
            {
                _loginpage = new Test_123RepositoryFolders.LoginPageAppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6c85d5fe-314c-4a76-b5db-65d7fe984dd9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("61c1d635-e1f2-4279-9f11-633fd60e54f0")]
            public virtual Test_123RepositoryFolders.LoginPageAppFolder LoginPage
            {
                get { return _loginpage; }
            }
        }

        /// <summary>
        /// The LoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("61c1d635-e1f2-4279-9f11-633fd60e54f0")]
        public partial class LoginPageAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/form[@controlname='LoginForm']", parentFolder, 30000, null, true, "61c1d635-e1f2-4279-9f11-633fd60e54f0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("61c1d635-e1f2-4279-9f11-633fd60e54f0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("61c1d635-e1f2-4279-9f11-633fd60e54f0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}